### PR TITLE
add options to compareImages

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by jamescryer** [comment]
The script as a syntax error, I can't run the tests nor the webpage with your changes.

**Comment by graingert** [comment]
@jamescryer odd, but the CI still passes?

**Comment by jamescryer** [comment]
There isn't any CI for this project.  Its one of the things I would like to fix but there are blockers on my side. That said, never a good idea to rely purely on CI feedback, manual sanity checks are always good practice.

**Comment by jamescryer** [comment]
I get the following script error `resemble.outputSettings is not a function` when clicking on the config buttons on the demo page.  Please test your changes.

**Comment by graingert** [comment]
yeah resemble.outputSettings is gone. It mutates global state.

**Comment by jamescryer** [comment]
There is a syntax error, and once that's fixed there are failing tests.  Let me know when you're done with your changes and have tested the code. The `resemble.outputSettings` change is a breaking API change, so would require a major bump release and downstream changes, I'm hesitant to proceed with that so please ensure it remains backward compatible if you wish to merge into master.

I'll review again in two weeks. Thanks.

**Comment by graingert** [comment]
@jamescryer can you give this one a go?

**Comment by jamescryer** [comment]
Thanks

**Pull request merged**
