### PR TITLE
Setting cross origin anonymous

### PR DESCRIPTION
**Pull request by denizkutluay**
The cross origin line moved into a weird line which is resulting in blocked remote sources. The line should be right after declaring hiddenImage.

### CODE REVIEW

**Comment by jamescryer** [comment]
Latest commit will remove the conditional CORS attribute all together -  I tested in FF Chrome, with relative, base64, same and x-origin images.  I saw no reason to have the if statement.

**Comment by benwick** [comment]
Without the if-Statement, Safari in iOS will throw a securtiy error and fail silently when using base64 data urls: "Cross-origin image load denied by Cross-Origin Resource Sharing policy." You should test for base64 encoded data...

**Comment by jamescryer** [comment]
Perhaps it should try/catch or test specifically for Safari.

**Comment by mcoenca** [comment]
Hey ! What's the fix for mobile safari ? It's not clear what if you are referring to :) Thanks !

**Pull request closed without merging**
