### PR TITLE
Feature/62 output diff portion from inputs

### PR DESCRIPTION
**Pull request by kamilbielawski**
This one solves #62 .
Of course please let me know if any changes are required.

### CODE REVIEW

**Comment by jamescryer** [comment]
Sorry for the late reply.  PR looks good, I think the `outputDiff` output setting might be better as `errorType: 'diffOnly'` to keep consistent with the other options. There is also a bug on the demo page where the other output errortypes don't re-draw correctly after `outputDiff` has been set to true.

**Comment by kamilbielawski** [comment]
Thank you for your response. I'll make the change and look into the issue within the next few days.

**Comment by kamilbielawski** [comment]
@jamescryer done;
One thing I'm not sure about is explicitly checking `errorType` in `copyPixel` and `copyGrayScalePixel`. An alternative would be to introduce a new flag that would be set in `outputSettings` when errorType passed in options would be `diffOnly`. However, we would then need to make sure to reset it if errorType is different, so it wouldn't necessary be cleaner in the end.

**Comment by jamescryer** [comment]
Explicitly checking errorType in copyPixel and copyGrayScalePixel seems ok to me, sometimes its best to keep it simple.

Thanks!

**Pull request merged**
